name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: geNAZt
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.state.genazt.me
          repository: gomint/website
          tags: latest